### PR TITLE
feature: Add search functionality

### LINKED ISSUE #11: Did you disable search?
I can't seem to get search to work, nor do I find any css references to it in this repo's files.

Tried by adding the following to `config.toml`:
```toml
 # Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"
[search]
include_title = true
include_description = true
```

### PR DESCRIPTION
**Pull request by x10an14**
As shown/described/instructed by Zola

Caveats:
- Commit also touches footer message, less ambiguous

Potential future TODOs:
- Not happy with search results UI/look - room for improvement
- Add a switch for this under `extra` section in config.toml?

Closes #11

### CODE REVIEW

**Comment by x10an14** [comment]
How it looks like on my machine:
2023-06-02T20:20:25,280292569+02:00

**Comment by syedzayyan** [comment]
Thanks for the PR. Adding it to the header makes it feels cluttered, maybe below the home page banner or a small icon that expands into a modal sort of thing would make more sense and with the new HTML updates it could be less Javascripty. Adding a switch is a must though.

**Comment by x10an14** [comment]
Force-pushed branch again to remove duplicate commit

>Adding it to the header makes it feels cluttered, maybe below the home page banner or a small icon that expands into a modal sort of thing would make more sense and with the new HTML updates it could be less Javascripty.

Sure, but that'll be for someone more proficient at JS than me to add =)

> Adding a switch is a must though.

I agree, but I got burned out on figuring out the search, so let's see if I can regain some motivation in some days =)
Anyone else are free to take a stab at it!

**Comment by x10an14** [comment]
If you want a UI input, I'd say putting socials in the footer might not only make more space, but also follow (in my anecdotal experience) more common conventions.

**Comment by syedzayyan** [comment]
I like the suggestion of the socials being in the footer. I'll try and do that.

> Sure, but that'll be for someone more proficient at JS than me to add =)
> Doesn't feel as cluttered to me, though

It won't if socials move to the footer. On that. I'll also try and fiddle with the search bar a bit to my liking!

Instead of pushing to the main. If you could push to "dev" it would be great for the future. If you could do a git pull before pushing you won't have to force push. I changed things around and your local files may have not been updated which causes conflicts. I am keeping this PR open for further discussion.

Thanks for the contributions! Open Source is hard, as everything is free. Don't burn yourself out, man. Do it till you enjoy it! Enjoyment is the only thing we get from it. :)

**Pull request merged**
